version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.7.0-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action-server:
    image: rasa/rasa-sdk:2.7.0
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    expose:
      - 5055